spring:
  freemarker:
    suffix: .ftl
    settings:
          classic_compatible: true
          datetime_format: yyyy-MM-dd HH:mm
          number_format: 0.##
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB