server:
  port: 8083
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo1?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 612915

  freemarker:
    suffix: .ftl
    settings:
          classic_compatible: true
          datetime_format: yyyy-MM-dd HH:mm:ss
          number_format: 0.##
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.lhm.pojo


#控制台打印sql语句
logging:
  level:
    com:
      lhm:
        mapper: debug
